#
# Module manifest for module 'Windows Sandbox Config'
#
# Generated by: Tim Small
#
# Generated on: 2020-12-04
#

@{

    RootModule         = "WindowsSandboxConfig.psm1"
    ModuleVersion      = "2020.12.0"
    # CompatiblePSEditions = @()
    GUID               = "9e855814-adbe-41a0-b578-31c982d4ac73"
    Author             = "Tim Small"
    CompanyName        = "Smalls.Online"
    Copyright          = "2020"
    Description        = "Create and manage Windows Sandbox config files."
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # ClrVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    RequiredAssemblies = "LibWindowsSandbox.dll"
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()

    # FunctionsToExport  = "*"
    # CmdletsToExport    = "*"
    # VariablesToExport  = "*"
    # AliasesToExport    = "*"

    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()

    PrivateData        = @{

        PSData = @{

            # Tags = @()

            # LicenseUri = ""

            ProjectUri = "https://github.com/Smalls1652/windows-sandbox-workspace"

            # IconUri = ''

            # ReleaseNotes = ''

            Prerelease = "alpha-01"
            
            # RequireLicenseAcceptance = $false

            # ExternalModuleDependencies = @()

        }

    }

    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''

}

